version: '3.7'
services:
# Add the catapp service
  catapp1:
    image: mikesir87/cats:1.0
    container_name: catapp1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.catapp1.rule=Host(`thomas-chateau.net`) && Path(`/cat1`) "
      - "traefik.http.routers.catapp1.entrypoints=web"
    networks:
      - netcatapp

# Add the catapp service
  catapp2:
    image: mikesir87/cats:1.0
    container_name: catapp2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.catapp2.rule=Host(`thomas-chateau.net`) && Path(`/cat2`) "
      - "traefik.http.routers.catapp2.entrypoints=web"
    networks:
      - netcatapp

# # Add the catapp service
#   catapp3:
#     image: mikesir87/cats:1.0
#     container_name: catapp3
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.catapp3.rule=Host(`thomas-chateau.net`)"
#       - "traefik.http.routers.catapp3.entrypoints=web"
#     networks:
#       - netcatapp

networks:
  netcatapp:
    external: 
      name: vps-traefik_webgateway